---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-jenkins-master
    image: leandelivery/docker-systemd:centos7
    privileged: true
    exposed_ports:
      - 8080/tcp
    published_ports:
      - 0.0.0.0:8888:8080/tcp
    groups:
      - rhel_family
      - jenkins_master
  - name: test-docker-ubuntu1804-jenkins-slave
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
      - jenkins_slaves
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  playbooks:
    verify: ../resources/tests/verify.yml
scenario:
  name: default
verifier:
  name: ansible
  lint:
    name: ansible-lint
