---
- name: Converge
  hosts: jenkins_slaves
  vars:
    master_host: '{{ master_host_ip }}'
    slave_linux_host: '{{ slave_host_ip }}'
    slave_agent_name: '{{ inventory_hostname }}'
    slave_linux_jenkins_cred_id: slave_node
    slave_linux_jenkins_username: slave
    slave_linux_user_group: slave
    slave_linux_jenkins_password: password
    slave_linux_jenkins_public_key: '{{ jenkins_slave_key }}'
  pre_tasks:
    - set_fact:
        master_host_ip: >-
          {{ hostvars[groups['jenkins_master'][0]].inventory_hostname }}
        slave_host_ip: '{{ ansible_hostname }}'
        jenkins_slave_key: >-
          {{ hostvars[groups['jenkins_master'][0]].jenkins_slave_key }}
  roles:
    - role: ansible-role-jenkins-slave
