---
- name: Get Jenkins master
  hosts: all
  tasks:
    - name: setup
      setup:

- name: Deal with the public key
  hosts: jenkins_master
  tasks:
    - name: Slurp the public key
      slurp:
        src: /tmp/jenkins_key.pub
      register: jenkins_key_pub

    - name: Save the public key
      set_fact:
        jenkins_slave_key: >-
          {{ jenkins_key_pub['content'] | b64decode }}

- name: Converge
  hosts: jenkins_slaves
  vars:
    master_host: '{{ hostvars[groups["jenkins_master"][0]].ansible_default_ipv4.address }}'
    slave_linux_host: '{{ hostvars[groups["jenkins_slaves"][0]].ansible_default_ipv4.address }}'
    slave_agent_name: '{{ inventory_hostname }}'
    slave_linux_jenkins_cred_id: slave_node
    slave_linux_jenkins_username: slave
    slave_linux_user_group: slave
    slave_linux_jenkins_password: password
  roles:
    - role: ansible-role-jenkins-slave
