---
- name: Install jenkins-slave on all slave nodes
  hosts: jenkins_slaves
  vars:
    master_host: '{{ hostvars[groups["jenkins_master"][0]].ansible_host }}'
    slave_linux_host: '{{ ansible_hostname }}'
    slave_agent_name: '{{ inventory_hostname }}'
    slave_linux_jenkins_cred_id: slave_node
    slave_linux_jenkins_username: slave
    slave_linux_user_group: slave
    slave_linux_jenkins_password: password
  roles:
    - role: ansible-role-jenkins-slave
