---
- name: "Prepare Ubuntu / Debian"
  hosts: debian_family
  gather_facts: false
  tasks:
    - name: "Install python for Ansible"
      raw: test -e /usr/bin/python || (apt install -y python-minimal python-zipstream)
      become: true
      changed_when: false

- name: "Prepare RHEL"
  hosts: rhel_family
  gather_facts: false
  tasks:
    - name: "Install python for Ansible"
      raw: test -e /usr/bin/python || (yum install -y python2 python-simplejson)
      become: true
      changed_when: false

- name: "Install Oracle-Java"
  hosts: all
  roles:
    - role: lean_delivery.java

# Workaround for centos in docker that fails with
# yum error: package does not match intended download.
- name: "Workaround centos yum issue"
  hosts: rhel_family
  tasks:
    - name: "Clean yum cache"
      command: yum --enablerepo=updates clean metadata
      become: true
      args:
        warn: false
      changed_when: false

- name: "Prepare Jenkins"
  hosts: jenkins_master
  vars:
    jenkins2_credentials:
      slave:
        type: 'password'
        id: 'slave_node'
        username: 'slave'
        password: 'password'
        description: 'credentials for slave node'
  roles:
    - role: lean_delivery.jenkins
